# Generated by Django 5.1.5 on 2025-01-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tasks_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='task',
        ),
    ]
