# Generated by Django 5.1.5 on 2025-01-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_tasks_task_rename_tasks_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
